<?php

namespace App\Http\Controllers\PublicSite;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class SiteAuditPageController extends Controller
{
    public function __invoke(Request $request): View
    {
        $url = trim((string) $request->query('url', ''));

        return view('public.site-audit.show', [
            'bootstrap' => [
                'url' => $url,
                'apiUrl' => url('/api/public/site-audits'),
                'i18n' => [
                    'title' => __('public.site_audit.page_heading'),
                    'page_lead' => __('public.site_audit.page_lead'),
                    'loading' => __('public.site_audit.loading'),
                    'loading_hint' => __('public.site_audit.loading_hint'),
                    'error_generic' => __('public.site_audit.error_generic'),
                    'error_missing_url' => __('public.site_audit.error_missing_url'),
                    'error_throttle' => __('public.site_audit.error_throttle'),
                    'retry' => __('public.site_audit.retry'),
                    'back_home' => __('public.site_audit.back_home'),
                    'cta_register' => __('public.site_audit.cta_register'),
                    'locked_teaser' => __('public.site_audit.locked_teaser'),
                    'locked_cta' => __('public.site_audit.locked_cta'),
                    'footer_label' => __('public.site_audit.footer_label'),
                    'footer_title' => __('public.site_audit.footer_title'),
                    'footer_lead' => __('public.site_audit.footer_lead'),
                    'footer_point_1' => __('public.site_audit.footer_point_1'),
                    'footer_point_2' => __('public.site_audit.footer_point_2'),
                    'footer_point_3' => __('public.site_audit.footer_point_3'),
                    'status_ready' => __('public.site_audit.status_ready'),
                    'status_failed' => __('public.site_audit.status_failed'),
                    'section_server' => __('public.site_audit.section_server'),
                    'section_indexing' => __('public.site_audit.section_indexing'),
                    'section_content' => __('public.site_audit.section_content'),
                    'section_metadata' => __('public.site_audit.section_metadata'),
                    'label_page_title' => __('public.site_audit.label_page_title'),
                    'label_page_description' => __('public.site_audit.label_page_description'),
                    'label_headings' => __('public.site_audit.label_headings'),
                    'label_text_length' => __('public.site_audit.label_text_length'),
                    'label_word_count' => __('public.site_audit.label_word_count'),
                    'label_nausea' => __('public.site_audit.label_nausea'),
                    'label_html_size' => __('public.site_audit.label_html_size'),
                    'label_external_links' => __('public.site_audit.label_external_links'),
                    'label_internal_links' => __('public.site_audit.label_internal_links'),
                    'label_adult_content' => __('public.site_audit.label_adult_content'),
                    'label_open_graph_block' => __('public.site_audit.label_open_graph_block'),
                    'label_schema_org' => __('public.site_audit.label_schema_org'),
                    'content_length_tags' => __('public.site_audit.content_length_tags'),
                    'content_tags_found' => __('public.site_audit.content_tags_found'),
                    'length_rating_good' => __('public.site_audit.length_rating_good'),
                    'length_rating_bad' => __('public.site_audit.length_rating_bad'),
                    'length_recommended' => __('public.site_audit.length_recommended'),
                    'title_length_good_hint' => __('public.site_audit.title_length_good_hint'),
                    'title_length_short_hint' => __('public.site_audit.title_length_short_hint'),
                    'title_length_long_hint' => __('public.site_audit.title_length_long_hint'),
                    'description_length_good_hint' => __('public.site_audit.description_length_good_hint'),
                    'description_length_short_hint' => __('public.site_audit.description_length_short_hint'),
                    'description_length_long_hint' => __('public.site_audit.description_length_long_hint'),
                    'content_chars' => __('public.site_audit.content_chars'),
                    'content_words' => __('public.site_audit.content_words'),
                    'content_nausea' => __('public.site_audit.content_nausea'),
                    'content_html_size' => __('public.site_audit.content_html_size'),
                    'content_links' => __('public.site_audit.content_links'),
                    'content_adult_yes' => __('public.site_audit.content_adult_yes'),
                    'content_adult_no' => __('public.site_audit.content_adult_no'),
                    'content_schema_no' => __('public.site_audit.content_schema_no'),
                    'content_og_missing' => __('public.site_audit.content_og_missing'),
                    'content_headings_summary' => __('public.site_audit.content_headings_summary'),
                    'content_heading_type' => __('public.site_audit.content_heading_type'),
                    'content_heading_text' => __('public.site_audit.content_heading_text'),
                    'label_response_time' => __('public.site_audit.label_response_time'),
                    'response_time_excellent' => __('public.site_audit.response_time_excellent'),
                    'response_time_excellent_hint' => __('public.site_audit.response_time_excellent_hint'),
                    'response_time_good' => __('public.site_audit.response_time_good'),
                    'response_time_good_hint' => __('public.site_audit.response_time_good_hint'),
                    'response_time_bad' => __('public.site_audit.response_time_bad'),
                    'response_time_bad_hint' => __('public.site_audit.response_time_bad_hint'),
                    'response_time_very_bad' => __('public.site_audit.response_time_very_bad'),
                    'response_time_very_bad_hint' => __('public.site_audit.response_time_very_bad_hint'),
                    'label_http_status' => __('public.site_audit.label_http_status'),
                    'label_ssl' => __('public.site_audit.label_ssl'),
                    'ssl_ok' => __('public.site_audit.ssl_ok'),
                    'ssl_missing' => __('public.site_audit.ssl_missing'),
                    'ssl_issuer' => __('public.site_audit.ssl_issuer'),
                    'ssl_subject' => __('public.site_audit.ssl_subject'),
                    'ssl_valid_to' => __('public.site_audit.ssl_valid_to'),
                    'ssl_days_left' => __('public.site_audit.ssl_days_left'),
                    'ssl_expired' => __('public.site_audit.ssl_expired'),
                    'label_www_redirect' => __('public.site_audit.label_www_redirect'),
                    'label_not_found_status' => __('public.site_audit.label_not_found_status'),
                    'label_not_found_home_link' => __('public.site_audit.label_not_found_home_link'),
                    'label_ip' => __('public.site_audit.label_ip'),
                    'label_meta_robots' => __('public.site_audit.label_meta_robots'),
                    'label_robots' => __('public.site_audit.label_robots'),
                    'label_robots_indexing' => __('public.site_audit.label_robots_indexing'),
                    'label_sitemap' => __('public.site_audit.label_sitemap'),
                    'label_title' => __('public.site_audit.label_title'),
                    'label_description' => __('public.site_audit.label_description'),
                    'label_viewport' => __('public.site_audit.label_viewport'),
                    'label_charset' => __('public.site_audit.label_charset'),
                    'label_canonical' => __('public.site_audit.label_canonical'),
                    'label_og_title' => __('public.site_audit.label_og_title'),
                    'label_og_description' => __('public.site_audit.label_og_description'),
                    'label_og_image' => __('public.site_audit.label_og_image'),
                    'label_favicon' => __('public.site_audit.label_favicon'),
                    'label_apple_touch_icon' => __('public.site_audit.label_apple_touch_icon'),
                    'label_google_analytics' => __('public.site_audit.label_google_analytics'),
                    'label_yandex_metrika' => __('public.site_audit.label_yandex_metrika'),
                    'present' => __('public.site_audit.present'),
                    'missing' => __('public.site_audit.missing'),
                    'yes' => __('public.site_audit.yes'),
                    'no' => __('public.site_audit.no'),
                    'ok' => __('public.site_audit.ok'),
                    'ms' => __('public.site_audit.ms'),
                    'status_code' => __('public.site_audit.status_code'),
                    'home_url' => localized_route('public.home'),
                    'register_url' => url('/app/register'),
                ],
            ],
        ]);
    }
}
